language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3

matrix:
  allow_failures:
    # Master may fail for any reason, on any ruby version.
    # It's good to keep an eye on it in case if fails because of us.
    - rvm: 2.3.8
      env: REDMINE_VER=master DB=mysql
    - rvm: 2.4.5
      env: REDMINE_VER=master DB=mysql
    - rvm: 2.5.3
      env: REDMINE_VER=master DB=mysql
    - rvm: 2.2.10
      env: REDMINE_VER=master DB=postgresql
    - rvm: 2.3.8
      env: REDMINE_VER=master DB=postgresql
    - rvm: 2.4.5
      env: REDMINE_VER=master DB=postgresql
    - rvm: 2.5.3
      env: REDMINE_VER=master DB=postgresql

env:
  - REDMINE_VER=4.0-stable DB=mysql
  - REDMINE_VER=4.0-stable DB=postgresql
  - REDMINE_VER=master DB=mysql
  - REDMINE_VER=master DB=postgresql

before_install:
  - export PLUGIN_NAME=redmine_tags
  - export REDMINE_PATH=$HOME/redmine
  - export BUNDLE_GEMFILE=$REDMINE_PATH/Gemfile
  - git clone https://github.com/redmine/redmine.git --branch $REDMINE_VER --depth 1 $REDMINE_PATH
  # TODO: this needs to be a `mv` once the testing plugin is removed.
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - make -f plugins/redmine_tags/Makefile prepare

script:
  - make -f plugins/redmine_tags/Makefile ci
